paths:
  static: ''
  uploads: uploads
timezone: Europe/London
markdown:
  engine: commonmark
  options:
    html: true
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  episodes:
    path: episodes
    icon: barcode
